version: '3.8'

services:
  wrapper-manager:
    build: .
    container_name: wrapper-manager
    command: [
      "--host", "localhost",
      "--port", "8080",
      "--mirror", "false"
    ]
    ports:
      - "8080:8080"